client/urls.py
from django.urls import path
from .views import UserRegister, user_login, user_logout

app_name = 'client'

urlpatterns = [
    path('user-register/', UserRegister.as_view(), name="user-register"),
    path("user-login/", user_login, name="user-login"),
    path("user-logout/", user_logout, name="user-logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('client/', include("client.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import compare, download, IndexView, service, about_view
app_name = "main"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("compare/", compare, name="compare"),
    path("done/", download, name="done"),
    path("service/<str:service_name>/", service, name='service'),
    path("about/", about_view, name="about"),
    
]

client/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .validators import PhoneValidator

class User(AbstractUser):
    REQUIRED_FIELDS = ['phone']
    phone = models.CharField(max_length=13, unique=True, null=True)#, validators=[PhoneValidator()])
    company_name = models.CharField(max_length=256, null=True)

    def __init__(self, *args, **kwargs):
        super(User, self).__init__(*args, **kwargs)
        self.old_password = self.password


    def save(self, *args, **kwargs):
        if self._state.adding or (self.password != self.old_password):
            super().set_password(self.password)
        super().save(*args, **kwargs)

client/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from .models import User

class UserForm(forms.ModelForm):
    confirm = forms.CharField(max_length=128, validators=[MinLengthValidator(6)], widget=forms.PasswordInput(), required=True)
    password = forms.CharField(max_length=128, validators=[MinLengthValidator(6)], widget=forms.PasswordInput(), required=True)

    class Meta:
        model = User
        fields = ['company_name', "username", 'phone',  'password', 'confirm']
        help_texts = {
            'username': None,
        }
        widgets = {
            'phone': forms.TextInput(
                attrs={
                    'placeholder': '+988',
                }
            )
        }
    # def clean(self):
    #     print(self.cleaned_data)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=40)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, validators=[MinLengthValidator(6)])

client/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required

from .permissions import notLoginRequiredMixin
from .models import User
from .forms import UserForm, LoginForm
from .decorators import notloggedin_required

class UserRegister(notLoginRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('main:done')
    template_name = 'user_register.html'
    login_url = 'main:index' #if user is logged in redirect to login_url
    
    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if data['password'] != data['confirm']:
                ValidationError("Password confirmation is not valid!")
            del data['confirm']
            user = User(**data)
            
            user.set_password(user.password)
            user.save()
            return redirect("client:user-login")
        return super().post(request)


@notloggedin_required
def user_login(request):
    # request.title = 'Login'
    form = LoginForm()
    if request.POST:
        form  = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('main:index')
            
            form.add_error('username', 'Username or Password is not valid')
    return render(request, 'login.html', {'form':form})


@login_required
def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("client:user-login")
    # return redirect("client:user-login")

client/templates/forms.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{%load static%}
{%block style%}<link rel="stylesheet" type="text/css" href="{%static 'css/client.css'%}"/>{%endblock%}

{%block content%}
    <div class="pt-5 d-flex justify-content-center" >
        <div class="p-lg-5 border border-3 border-light bg- bg-opacity-10 rounded p-5"  id="form-container">
            <form action="{%block url%}{%endblock%}" method="post" id="reg__form" >
                {% csrf_token %}
                    <div class="form">
                        {%crispy form%}
                        <div class="pt-3 d-flex justify-content-center">
                            <button type="submit" class="btn btn-lg btn-success">{%block btn_name%}{%endblock%}</button>
                        </div>
                    </div>
                    
            </form>
        </div>
    </div>
    
{%endblock%}

{%block js%} <script src="{%static 'js/client.js'%}"></script> {%endblock%}

client/templates/login.html
{%extends 'forms.html'%}

{%block url%}
    {%url 'client:user-login'%}
{%endblock%}

{%block btn_name%}Login{%endblock%}

client/templates/profile.html
{%extends 'base.html'%}

{%block content%}


{%endblock%}

client/templates/user_register.html
{%extends 'forms.html'%}


{%block url%}
    {%url 'client:user-register'%}
{%endblock%}

{%block btn_name%}Submit{%endblock%}