config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('client/', include("client.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import compare, download, IndexView, service, about_view
app_name = "main"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("compare/", compare, name="compare"),
    path("done/", download, name="done"),
    path("service/<str:service_name>/", service, name='service'),
    path("about/", about_view, name="about"),
    
]

main/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files import File
from .helpers import upload_file_name

class Company(models.Model):
    name = models.CharField(max_length=256, null=True)
    ceo = models.ForeignKey('client.User', on_delete=models.SET_NULL, null=True, related_name='company_ceo')
    staffs = models.ManyToManyField('client.User', related_name="company")


class Service(models.Model):
    name = models.CharField(max_length=256, null=True)
    desc = models.TextField(max_length=500, blank=True, null=True)
    icon = models.ImageField(upload_to=upload_file_name, null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def save(self,**kwargs):                         # to compress the img files!!
        if not self.icon.closed:                      #if img exists
            img = Image.open(self.icon)               #open img via Pillow
            img.thumbnail((100,100),Image.ANTIALIAS) #compress px till 100 to 100 saves proporsion donot worry!
            tmp = BytesIO()                          #Buffer massive!
            img.save(tmp,"PNG")                      #save img to massive that created before! & and change type of file to png
            #tmp.seek(0)

            self.img = File(tmp,'t.png') #telling django upload to img new file tmp-file <<t>> does not metter because we have uploaded_file_name

        return super().save(**kwargs)

main/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div,Submit, Button


COL_TO_NUM = (
    ("0","A"), ("1","B"), ("2","C"), ("3","D"),
    ("4","E"), ("5","F"), ("6","G"), ("7","H"),
    ("8","I"), ("9","J"), ("10","K"), ("11","L"),
    ("12","M"), ("13","N"), ("14","O"), ("15","P"),
    ("16","Q"), ("17","R"), ("18","S"), ("19","T"),
    ("20","Y"), ("21","V"), ("22","W"), ("23","X"),
    ("24","Y"), ("25","Z")
    #TODO case !?
)

class ComparisonForm(forms.Form):

    first_med_col = forms.ChoiceField(label='First medicine column', choices=COL_TO_NUM)
    first_co_col = forms.ChoiceField(label='First manufacture column', choices=COL_TO_NUM)
    first_file = forms.FileField()

    second_med_col = forms.ChoiceField(label="Second medicine column", choices=COL_TO_NUM)
    second_co_col = forms.ChoiceField(label='Second manufacture column', choices=COL_TO_NUM)
    second_file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div('first_med_col', "first_co_col", "first_file", css_class='col-sm-6 col-12 border p-5'),
                Div('second_med_col', "second_co_col", "second_file", css_class='col-sm-6 col-12 border p-5'),      
            css_class='row p-2 position-relative'), 

            Div(
                Submit('submit', 'COMPARE', css_class="btn btn-success btn-lg "),
                css_class="d-flex justify-content-center")
        )
 

main/views.py
from multiprocessing import Process
from os import kill
from signal import SIGTERM, SIGINT


from datetime import datetime
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .compare import make_comparison
from .forms import ComparisonForm 
from .models import Service


class IndexView(LoginRequiredMixin, ListView):
    model = Service
    template_name = "pages/index.html"


@login_required
def service(request, service_name):
    if service_name == 'Compare':
        return redirect('main:compare')
    return redirect("main:index")

@login_required
def about_view(request):
    return render(request, 'pages/about.html')
from django.http import JsonResponse

@login_required
def compare(request):

    if request.method == "POST":
        data = ComparisonForm(data=request.POST, files=request.FILES)
        if data.is_valid():

            start = datetime.now()
            try:
                make_comparison(data, request)
            except Exception as ex:
                return redirect("main:compare")

            # compare_thread = Process(target=make_comparison, args=(data, request), daemon=True)
            # compare_thread.start()
            # kill(compare_thread.pid, SIGKILL)
            # compare_thread.join()
            # return redirect("main:loading", pid=compare_thread.pid)
            print(datetime.now() - start,)
            # return JsonResponse({"PID":compare_thread.pid})
            return redirect("main:done")

    context = {}
    context['form'] = ComparisonForm()
    return render(request, "pages/compare.html", context)


@login_required
def download(request):
    context = {}
    context['COMPARISON_FILE'] = f'/media/sample_{request.user}.xlsx'
    return render( request, "pages/result.html", context)

main/templates/parts/footer.html
<footer class="mt-5 text-center " >
    <div class="d-flex flex-row justify-content-center m-1">
        <a class="nav-link fw-bolder" href="#">Home</a>
        <a class="nav-link mx-3 fw-bolder" href="#">Contact</a>
        <a class="nav-link fw-bolder" href="#">Features</a>

    </div>
	<div>
	    <p style="opacity: 0.75; margin: 0%;"> Copyright @ <span id="year"></span> All Rights Reserved.</p>
    </div>

</footer>

<style>
   footer{
    position:absolute;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100%;
    z-index: -1;
    box-shadow:   inset 0.1rem 0.1rem 3em rgba(0,0,0,0.3),
            0 0  0 2px rgb(255,255,255),
            0 -3em 3em rgba(0,0,0,0.1);

   }

   @media (max-width: 576px) {
    footer{
        margin-top: 100px;
        position: relative !important;
    }
    
   }
</style>

<script>
    document.getElementById("year").innerText = new Date().getFullYear()
</script>

main/templates/parts/header.html
<nav class="navbar navbar-expand-lg  px-5 border-bottom border-3">
    <div class="container-fluid">
      <a class="navbar-brand fw-bolder" href="{%url 'main:index'%}">TakeTheRisk</a> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav me-auto"></ul>
        <div class="d-flex">
            <ul class="navbar-nav ">
                <li class="nav-item">
                  
                    <a class="nav-link fw-bolder {%if request.path == '' %} active{%endif%}" href="{%url 'main:index'%}">Home</a>
                  </li>
                  <li class="nav-item fw-bolder {%if request.path == '/features/' %} active{%endif%}">
                    <a class="nav-link" href="#">Features</a>
                  </li>
                  <!-- <li class="nav-item  fw-bolder {%if request.path %} active{%endif%}">
                    <a class="nav-link" href="#">Pricing</a>
                  </li> -->
                  <li class="nav-item fw-bolder {%if request.path == '/about/' %} active{%endif%}">
                    <a class="nav-link" href="{%url 'main:about'%}">About</a>
                  </li>

            </ul>
        </div>
        <!-- <form class="d-flex">
          <input class="form-control me-sm-2" type="search" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </div>
  </nav>