config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path('client/', include("client.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import compare, download, IndexView, service, about_view
app_name = "main"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("compare/", compare, name="compare"),
    path("done/", download, name="done"),
    path("service/<str:service_name>/", service, name='service'),
    path("about/", about_view, name="about"),
    
]

main/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files import File
from .helpers import upload_file_name

class Company(models.Model):
    name = models.CharField(max_length=256, null=True)
    ceo = models.ForeignKey('client.User', on_delete=models.SET_NULL, null=True, related_name='company_ceo')
    staffs = models.ManyToManyField('client.User', related_name="company")


class Service(models.Model):
    name = models.CharField(max_length=256, null=True)
    desc = models.TextField(max_length=500, blank=True, null=True)
    icon = models.ImageField(upload_to=upload_file_name, null=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def save(self,**kwargs):                         # to compress the img files!!
        if not self.icon.closed:                      #if img exists
            img = Image.open(self.icon)               #open img via Pillow
            img.thumbnail((100,100),Image.ANTIALIAS) #compress px till 100 to 100 saves proporsion donot worry!
            tmp = BytesIO()                          #Buffer massive!
            img.save(tmp,"PNG")                      #save img to massive that created before! & and change type of file to png
            #tmp.seek(0)

            self.img = File(tmp,'t.png') #telling django upload to img new file tmp-file <<t>> does not metter because we have uploaded_file_name

        return super().save(**kwargs)

main/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div,Submit, Button


COL_TO_NUM = (
    ("0","A"), ("1","B"), ("2","C"), ("3","D"),
    ("4","E"), ("5","F"), ("6","G"), ("7","H"),
    ("8","I"), ("9","J"), ("10","K"), ("11","L"),
    ("12","M"), ("13","N"), ("14","O"), ("15","P"),
    ("16","Q"), ("17","R"), ("18","S"), ("19","T"),
    ("20","Y"), ("21","V"), ("22","W"), ("23","X"),
    ("24","Y"), ("25","Z")
    #TODO case !?
)

class ComparisonForm(forms.Form):

    first_med_col = forms.ChoiceField(label='First medicine column', choices=COL_TO_NUM)
    first_co_col = forms.ChoiceField(label='First manufacture column', choices=COL_TO_NUM)
    first_file = forms.FileField()

    second_med_col = forms.ChoiceField(label="Second medicine column", choices=COL_TO_NUM)
    second_co_col = forms.ChoiceField(label='Second manufacture column', choices=COL_TO_NUM)
    second_file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div('first_med_col', "first_co_col", "first_file", css_class='col-sm-6 col-12 border p-5'),
                Div('second_med_col', "second_co_col", "second_file", css_class='col-sm-6 col-12 border p-5'),      
            css_class='row p-2 position-relative'), 

            Div(
                Submit('submit', 'COMPARE', css_class="btn btn-success btn-lg "),
                css_class="d-flex justify-content-center")
        )
 

main/views.py
from multiprocessing import Process
from os import kill
from signal import SIGTERM, SIGINT


from datetime import datetime
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .compare import make_comparison
from .forms import ComparisonForm 
from .models import Service


class IndexView(LoginRequiredMixin, ListView):
    model = Service
    template_name = "pages/index.html"


@login_required
def service(request, service_name):
    if service_name == 'Compare':
        return redirect('main:compare')
    return redirect("main:index")

@login_required
def about_view(request):
    return render(request, 'pages/about.html')
from django.http import JsonResponse

@login_required
def compare(request):

    if request.method == "POST":
        data = ComparisonForm(data=request.POST, files=request.FILES)
        if data.is_valid():

            start = datetime.now()
            try:
                make_comparison(data, request)
            except Exception as ex:
                return redirect("main:compare")

            # compare_thread = Process(target=make_comparison, args=(data, request), daemon=True)
            # compare_thread.start()
            # kill(compare_thread.pid, SIGKILL)
            # compare_thread.join()
            # return redirect("main:loading", pid=compare_thread.pid)
            print(datetime.now() - start,)
            # return JsonResponse({"PID":compare_thread.pid})
            return redirect("main:done")

    context = {}
    context['form'] = ComparisonForm()
    return render(request, "pages/compare.html", context)


@login_required
def download(request):
    context = {}
    context['COMPARISON_FILE'] = f'/media/sample_{request.user}.xlsx'
    return render( request, "pages/result.html", context)

main/templates/pages/about.html
{%extends 'base.html'%}

{%block content%}
    <div class="d-flex  justify-content-center text-center py-5">
        <div class="border border-3 w-50 p-5" id="about">
            <h1 class="text-secondary">About us</h1>
            <p class="m-5">
                asdasd asdh ashdj ashkd haskjdh kjashdkjashdkj ashkdjhsajkdhjaskhdjk ashkjdhkasjh dkjashjdk hsajkdkah kdjhasjkh djkashk jdhaskjhd kjashdjkash d
                asldjaslkdj askljdlk asjlkd jalskj
                saldkkaslkdl; ask;ld kas;ldk 
                aslkd;laskd
            </p>
            <div class="d-flex flex-row justify-content-center">
                <button class="btn  btn-lg btn-outline-info mx-5 fw-bolder" style="width: 200px;">helo</button>
                <!-- <button class="btn  btn-lg btn-outline-success fw-bolder" style="width: 200px;">askjdklasd</button> -->
            </div>
        </div>
    </div>

{%endblock%}

main/templates/pages/compare.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{%load static%}
{%block content%}


        {% if form.errors %}
            <ul class="errors">
                {% for error in form.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="text-center pt-3">
            <h6  class="alert alert-info" >Please enter these types of EXCEL .xlsx .xlsm .xlmx .xltx</h6>
        </div>
        <form action="{%url 'main:compare'%}" method="post" enctype="multipart/form-data" class="uniForm">
            {%csrf_token%}
                {% crispy form %}
                <!-- {{form|crispy}} -->
        </form>
    
        <div style="display:none;" class="position-fixed text-center" id="loading-container"><div class="d-flex justify-content-end m-5"><button id="close-btn" type="button" class="btn btn-danger">Stop!</button></div><div id="loading"><div><div class="spinner-border text-danger" role="status"><span class="sr-only"></span></div><h4>Loading...</h4></div></div></div>


{%endblock%}

{%block js%}
    <script>
        $(function(){
            $('form').on('submit', function(e){
                $('#loading-container').css('display',"block")
                
            //     e.preventDefault()
            //     var formData = new FormData($('form').get(0))
            //     // $.post(window.location.href, formData, function(data) {
            //     //     alert(data, "GBJ");
            //     // });

            //    console.log(formData)
            //     $.ajax({
            //         headers:{
            //             "X-CSRFToken": '{{csrf_token}}',
            //         },
            //         url: window.location.href,
            //         processData: false,
            //         contentType: false,
            //         data: formData,
            //         method: 'POST',
            //         csrfmiddlewaretoken: '{{ csrf_token }}',
            //         success: (data) => {
            //             localStorage.setItem("pid", JSON.stringify(data['PID']))
            //             console.log(JSON.stringify(data));
            //         },
            //     })
            
            });

           
        })

        // $("#close-btn").on("click", function(e){
        //     $("#loading-container").css('display','none')
        //     var pid = localStorage.getItem('pid')
        //     alert("HELLO", pid)
        //     $.ajax({
        //         url: window.location.href,
        //         data:JSON.stringify({'pid':pid}),
        //         method: 'DELETE',
        //         success: (data) => {
        //                 localStorage.removeItem('pid')
        //                 console.log(JSON.stringify(data));
        //         },
        //     })
        //     window.stop()

        // });

        window.onpopstate = function() {
            $("#loading-container").css('display','none')
        }; history.pushState({}, '');

        
    // $("#close-btn").on("click", function(e){
    //     $.ajax({
    //         url: window.location.href,
              
    //         data: {"stop":true},
    //         method: 'GET',
    //         csrfmiddlewaretoken: '{{ csrf_token }}'
    //     })
    // });
    </script>
{%endblock%}

main/templates/pages/index.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{%load static%}
{%block content%}
<div class="container p-5">
  <div class="d-flex  justify-content-center ">
    <div class="row " >
    {%for service in object_list%}
    
      <div class="col-sm-12 col-lg-4 ">
        <a href="{%url 'main:service' service.name %}" class="position-relative text-secondary text-decoration-none" {%if not service.is_active%} style="z-index: -1;"{%endif%}>
          

            <div class="card m-2 border border-3 " style="border-radius:15%;">
              {%if not service.is_active%}
                <div class="position-absolute comming-soon ">
                  <h4 style="margin-top: 50%;" class="text-center fw-bolder">Comming Soon</h4>
                </div>
              {%endif%}
              <img src="{{service.icon.url}}" class="card-img-top p-5" alt="..." max-width="200px" >
              <div class="card-body">
                <h5 class="card-title text-center">{{service.name}}</h5>
                <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                <!-- <a href="#" class="btn btn-success">Go somewhere</a> -->
              </div>
            </div>
          </a>
      </div>
    
    {%endfor%}
    </div>
  </div>
</div>



{%endblock%}

main/templates/pages/result.html
{%extends "base.html"%}

{%block content%}
    
    {%if COMPARISON_FILE %}
        <div class="container p-5">
            <div class="container">
                <div class="d-flex justify-content-center">
                    <a href="{{ COMPARISON_FILE }}" class="btn btn-info btn-lg "><i class="icomoon icon-download"></i> Download</a>
                </div>
                <hr>
                <div class="d-flex justify-content-center">
                    <a href="{%url 'main:compare'%}" class="btn btn-warning btn-lg">&#171; Go Back </a>
                </div>
            </div>
        </div>
    {%endif%}
{%endblock%}